#!/usr/bin/env bash
# rotate-signing-material.sh — regenerate the org's name-bearing signing creds with
# clean neutral names, store them in 1Password, distribute to GitHub + Cloudsmith.
#
# The 1Password get/set helpers plus the generation, Cloudsmith-upload, and
# GitHub-distribution stages are all implemented. Run on a machine with op signed in
# (`eval $(op signin)`), gh authed (`gh auth login`), and gpg/jq/curl on PATH.
#
# What rotates (everything with a tool name baked in):
#   1. package-signing GPG key   -> GitHub secret GPG_PRIVATE_KEY on all repos
#   2. Cloudsmith repo-INDEX key -> generated by hand in the Cloudsmith UI (the key is
#      Cloudsmith-managed on this plan; the API won't accept a custom key). Stage 2 only
#      captures the resulting PUBLIC key into 1P + out/ and flags the re-import.
#   3. homebrew-tap PAT          -> minted by hand (no API), then distributed
# The Cloudsmith API key is NOT rotated (no name embedded) — read from 1P, distribute.
#
# ⚠️  Regenerating the index key (stage 2, in the UI) re-signs the apt/dnf index: every
#     machine that already ran setup.deb.sh / setup.rpm.sh must re-import the new public
#     key before its next update succeeds.
#
# Requires: op (signed in), gh (authed), gpg, jq, curl.

set -euo pipefail

# ------------------------------------------------------------------ config ----
REPOS=(gostow dot-dagger hud dstow)
# binary name per repo. A case-function, not `declare -A`, so this runs on the
# bash 3.2 that macOS ships (associative arrays need bash 4+).
bin_for() {
  case "$1" in
    gostow)     echo gostow ;;
    dot-dagger) echo dotd   ;;
    hud)        echo hud    ;;
    dstow)      echo dstow  ;;
    *) echo "unknown repo: $1" >&2; return 1 ;;
  esac
}
OP_VAULT="${OP_VAULT:-dev}"
CS_OWNER=rocne; CS_REPO=releases
EMAIL=rocne.ks@gmail.com
OUT_DIR="${OUT_DIR:-out}"

# neutral names — no tool baked in.
# (The index key is Cloudsmith-managed — it names its own key — so no IDX_UID here.)
PKG_UID="Rocne Scribner (rocne/releases package signing) <$EMAIL>"
PAT_NAME="rocne/homebrew-tap push (release-ci)"

# 1Password item titles
OP_PKG_ITEM="GPG package signing key (rocne/releases)"
OP_IDX_ITEM="GPG repository index signing key (Cloudsmith, rocne/releases)"
OP_PAT_ITEM="GitHub PAT — homebrew-tap"
OP_CS_ITEM="Cloudsmith API key"

# ============================================================================
# 1PASSWORD GETTERS / SETTERS  — the part you asked for. Tested syntax.
# ============================================================================

# op_get FIELD_REF  — read a single secret value.
# Uses op's secret-reference syntax: op://<vault>/<item>/<field>
# e.g. op_get "$OP_CS_ITEM/password"  ->  the Cloudsmith API key
op_get() { # ITEM/FIELD (relative to $OP_VAULT)
  op read "op://$OP_VAULT/$1"
}

# op_put_key ITEM_TITLE PRIV PUB FPR  — upsert a GPG keypair item.
# Multiline armored blocks go in via shell vars (integrity is preserved; only the
# 1P *UI* renders multiline oddly — the stored value is exact, verified by round-trip).
# Edits keep 1Password version history, so the previous key stays recoverable.
op_put_key() { # ITEM_TITLE PRIV PUB FPR
  local title="$1" priv="$2" pub="$3" fpr="$4"
  local -a f=(
    "private key[password]=$priv"
    "public key[text]=$pub"
    "fingerprint[text]=$fpr"
    "notesPlain=passphrase intentionally empty (CI can't unlock a protected key). Rotated by rotate-signing-material.sh."
  )
  if op item get "$title" --vault "$OP_VAULT" >/dev/null 2>&1; then
    op item edit   "$title" --vault "$OP_VAULT" "${f[@]}" >/dev/null
  else
    op item create --category "Secure Note" --title "$title" --vault "$OP_VAULT" "${f[@]}" >/dev/null
  fi
}

# op_put_token ITEM_TITLE VALUE [NOTE]  — upsert a single-secret item (PAT, etc.)
op_put_token() { # ITEM_TITLE VALUE [NOTE]
  local title="$1" val="$2" note="${3:-}"
  local -a f=( "credential[password]=$val" )
  [[ -n "$note" ]] && f+=( "notesPlain=$note" )
  if op item get "$title" --vault "$OP_VAULT" >/dev/null 2>&1; then
    op item edit   "$title" --vault "$OP_VAULT" "${f[@]}" >/dev/null
  else
    op item create --category "API Credential" --title "$title" --vault "$OP_VAULT" "${f[@]}" >/dev/null
  fi
}

# op_put_pub ITEM_TITLE PUB FPR  — upsert a PUBLIC-key-only reference item, for keys
# whose private half we don't hold (e.g. the Cloudsmith-managed index key). Clears any
# stale "private key" field a prior run may have left (non-fatal if it isn't there).
op_put_pub() { # ITEM_TITLE PUB FPR
  local title="$1" pub="$2" fpr="$3"
  local -a f=(
    "public key[text]=$pub"
    "fingerprint[text]=$fpr"
    "notesPlain=Cloudsmith-managed index signing key. Private half is held by Cloudsmith and cannot be exported. Rotated by rotate-signing-material.sh."
  )
  if op item get "$title" --vault "$OP_VAULT" >/dev/null 2>&1; then
    op item edit "$title" --vault "$OP_VAULT" "${f[@]}" >/dev/null
    op item edit "$title" --vault "$OP_VAULT" 'private key[delete]' >/dev/null 2>&1 || true
  else
    op item create --category "Secure Note" --title "$title" --vault "$OP_VAULT" "${f[@]}" >/dev/null
  fi
}

# op_get_pub ITEM_TITLE  — pull a stored public key back out (for committing).
op_get_pub() { op item get "$1" --vault "$OP_VAULT" --fields "public key" --reveal; }

# ============================================================================
# Generation + distribution — uses the op_* helpers above.
# ============================================================================

# Ephemeral GNUPGHOMEs created by gen_key, wiped on any exit so private key
# material never outlives the run on disk.
_TMP_HOMES=()
cleanup() {
  local d
  for d in "${_TMP_HOMES[@]:-}"; do
    [[ -n "$d" ]] && rm -rf "$d"
  done
}
trap cleanup EXIT

# preflight — assert tooling + auth, then load the Cloudsmith API key (needed in
# stages 2 and 4) into the global CS_KEY.
preflight() {
  local miss=0 t
  for t in op gh gpg jq curl; do
    command -v "$t" >/dev/null 2>&1 || { echo "missing required tool: $t" >&2; miss=1; }
  done
  [[ $miss -eq 0 ]] || exit 1

  op whoami >/dev/null 2>&1        || { echo "op is not signed in — run: eval \$(op signin)" >&2; exit 1; }
  op vault get "$OP_VAULT" >/dev/null 2>&1 || { echo "1Password vault not found: $OP_VAULT" >&2; exit 1; }
  gh auth status >/dev/null 2>&1   || { echo "gh is not authed — run: gh auth login" >&2; exit 1; }

  CS_KEY=$(op_get "$OP_CS_ITEM/password") \
    || { echo "could not read Cloudsmith API key from 1Password item: $OP_CS_ITEM" >&2; exit 1; }
  [[ -n "$CS_KEY" ]] || { echo "Cloudsmith API key is empty" >&2; exit 1; }

  mkdir -p "$OUT_DIR"
}

# gen_key UID  ->  sets REPLY_FPR / REPLY_PRIV / REPLY_PUB (globals).
# Generates in an EPHEMERAL GNUPGHOME (mktemp -d, chmod 700, wiped by the EXIT trap)
# so no private key ever lands on persistent disk. RSA-4096, sign-only, no expiry,
# EMPTY passphrase (CI cannot unlock a protected key).
gen_key() {
  local uid="$1" home
  home=$(mktemp -d); chmod 700 "$home"
  _TMP_HOMES+=("$home")
  GNUPGHOME=$home gpg --batch --pinentry-mode loopback --passphrase '' \
    --quick-generate-key "$uid" rsa4096 sign never
  REPLY_FPR=$(GNUPGHOME=$home gpg --list-secret-keys --with-colons "$uid" \
    | awk -F: '/^fpr:/{print $10; exit}')
  REPLY_PRIV=$(GNUPGHOME=$home gpg --batch --pinentry-mode loopback --passphrase '' \
    --armor --export-secret-keys "$REPLY_FPR")
  REPLY_PUB=$(GNUPGHOME=$home gpg --armor --export "$REPLY_FPR")
  rm -rf "$home"
}

# gh_set NAME VALUE — set a secret on every repo (personal acct = no org secrets;
# each repo needs its own copy).
gh_set() {
  local name="$1" val="$2" r
  for r in "${REPOS[@]}"; do
    printf '%s' "$val" | gh secret set "$name" --repo "$CS_OWNER/$r"
    echo "  set $name on $CS_OWNER/$r"
  done
}

# ---- STAGE 1: package key ----
stage_package_key() {
  echo "== stage 1: package-signing GPG key =="
  gen_key "$PKG_UID"
  op_put_key "$OP_PKG_ITEM" "$REPLY_PRIV" "$REPLY_PUB" "$REPLY_FPR"
  gh_set GPG_PRIVATE_KEY "$REPLY_PRIV"
  local r
  for r in "${REPOS[@]}"; do
    printf '%s\n' "$REPLY_PUB" > "$OUT_DIR/$(bin_for "$r")-signing-key.asc"
  done
  echo "  package key $REPLY_FPR rotated; pubkeys written to $OUT_DIR/"
}

# ---- STAGE 2: Cloudsmith repository-index key (Cloudsmith-managed) ----
# The apt/dnf index is signed server-side by a key Cloudsmith OWNS (see docs/SECRETS.md).
# On this plan you can't upload your own key via the API, so rotation is a manual
# "generate" in the Cloudsmith UI. This stage doesn't touch a private key — it captures
# the resulting PUBLIC key (from the public GET endpoint), records it in 1P, writes it
# out for distribution, and reminds you existing installs must re-import.
stage_index_key() {
  echo "== stage 2: Cloudsmith repository-index key (Cloudsmith-managed) =="
  cat <<EOF
  Cloudsmith owns the index signing key on this plan — you can't upload your own.
  To rotate it, regenerate it by hand in the web UI:
    cloudsmith.io -> repo $CS_OWNER/$CS_REPO -> Settings -> Security (GPG signing)
    -> generate a new key.
  ⚠️  This re-signs the apt/dnf index: every machine that already imported the old
      key must re-import the new public key before its next 'apt update' / 'dnf'.
EOF
  local ans
  read -rp "Have you generated the new key in the UI? Type 'yes' to capture it (else skip): " ans
  [[ "$ans" == "yes" ]] || { echo "  skipped stage 2."; return 0; }

  # Read the key Cloudsmith is currently signing with (public endpoint, no auth needed).
  local resp fpr pub
  resp=$(curl -sS "https://api.cloudsmith.io/v1/repos/$CS_OWNER/$CS_REPO/gpg/" || true)
  fpr=$(printf '%s' "$resp" | jq -r '.fingerprint // empty')
  pub=$(printf '%s' "$resp" | jq -r '.public_key // empty')
  if [[ -z "$fpr" || -z "$pub" ]]; then
    echo "  could not read the current Cloudsmith index key:" >&2
    printf '%s\n' "$resp" >&2
    return 1
  fi
  echo "  live index key fingerprint: $fpr"

  # Record the public key in 1P (no private half exists on our side) and write it out.
  op_put_pub "$OP_IDX_ITEM" "$pub" "$fpr"
  printf '%s\n' "$pub" > "$OUT_DIR/repo-signing-key.asc"
  echo "  public key stored in 1Password ($OP_IDX_ITEM) + written to $OUT_DIR/repo-signing-key.asc"
  echo "  ⚠️  announce: existing apt/dnf users must re-import this key before their next update."
}

# ---- STAGE 3: homebrew PAT (manual mint — GitHub has no create-PAT API) ----
stage_homebrew_pat() {
  echo "== stage 3: homebrew-tap PAT (manual mint) =="
  cat <<EOF
  GitHub has no create-PAT API — mint a fine-grained token by hand:
    1. Open: https://github.com/settings/personal-access-tokens/new
    2. Token name:        $PAT_NAME
    3. Resource owner:    $CS_OWNER
    4. Expiration:        1 year (max); set a reminder to rotate before it lapses
    5. Repository access: Only select repositories -> $CS_OWNER/homebrew-tap
    6. Permissions:       Repository -> Contents: Read and write
    7. Generate, then paste it below.
EOF
  local pat push
  read -rsp "  paste PAT (input hidden, empty to skip): " pat; echo
  [[ -n "$pat" ]] || { echo "  no PAT entered; skipped stage 3."; return 0; }

  push=$(GH_TOKEN="$pat" gh api "repos/$CS_OWNER/homebrew-tap" --jq '.permissions.push') \
    || { echo "  PAT could not read $CS_OWNER/homebrew-tap — check the token." >&2; exit 1; }
  [[ "$push" == "true" ]] \
    || { echo "  PAT lacks push (Contents: write) on $CS_OWNER/homebrew-tap (push=$push)." >&2; exit 1; }

  op_put_token "$OP_PAT_ITEM" "$pat" \
    "fine-grained; Contents:rw on $CS_OWNER/homebrew-tap; expires 1y — rotate before expiry"
  gh_set HOMEBREW_TAP_GITHUB_TOKEN "$pat"
  echo "  PAT verified (push=true), stored in 1Password, distributed."
}

# ---- STAGE 4: Cloudsmith API key (distribute, don't rotate) ----
stage_cloudsmith_key() {
  echo "== stage 4: Cloudsmith API key (distribute, not rotated) =="
  gh_set CLOUDSMITH_API_KEY "$CS_KEY"
  echo "  Cloudsmith API key distributed."
}

# ---- AFTER: non-secret follow-ups (printed, done by hand) ----
after_notes() {
  cat <<EOF

== done. remaining non-secret follow-ups ==
  1. Package key: commit $OUT_DIR/<bin>-signing-key.asc to each repo root
       bin per repo: $(for r in "${REPOS[@]}"; do printf '%s=%s ' "$r" "$(bin_for "$r")"; done)
     and confirm it's listed under release.extra_files in each goreleaser config.
  2. Index key: nothing to commit — Cloudsmith serves its public key via the hosted
     setup.deb.sh / setup.rpm.sh, so new installs get it automatically.
     $OUT_DIR/repo-signing-key.asc is a reference copy only (also in 1Password).
  3. If the index key was rotated: announce it — existing apt/dnf users must
     re-import (re-run the Cloudsmith setup script) before their next update.
  4. Open the package-key PRs (one per repo) for the committed public keys.
EOF
}

# main [STAGE...] — run the named stages (1-4) in order; no args runs all four.
# e.g. `rotate-signing-material.sh 3 4` runs only the PAT + Cloudsmith-key stages,
# so a partial run can be resumed without re-rotating the earlier keys.
main() {
  preflight
  local stages=( "$@" ) s
  [[ ${#stages[@]} -eq 0 ]] && stages=(1 2 3 4)
  for s in "${stages[@]}"; do
    case "$s" in
      1) stage_package_key   ;;
      2) stage_index_key     ;;
      3) stage_homebrew_pat  ;;
      4) stage_cloudsmith_key ;;
      *) echo "unknown stage: $s (valid: 1 2 3 4)" >&2; exit 1 ;;
    esac
  done
  after_notes
}

main "$@"
